receivers:
  otlp:
    protocols:
      grpc:

exporters:
  awsxray:
    region: us-west-2
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]

  telemetry:
    logs:
      level: debug